# Formatting Data

- Using exportables from `toast`, this notebook reformats it to the desired format which is directly uploadable into AIO system.

### Handling Menu

Importing Datasets (Desired Format)

In [20]:
import pandas as pd

# Load the Excel file without reading any sheets yet
xl = pd.ExcelFile("menu_desired_format/menu_desired.xlsx")

# Print the names of all the sheets in the Excel file
print(xl.sheet_names)

['Menu', 'Category', 'Category Items', 'Item', 'Item Modifiers', 'Modifier', 'Modifier Option', 'Modifier ModifierOptions', 'Modifier Group', 'Setting', 'Visibility Setting', 'Day Schedule', 'Category ModifierGroups', 'Category Modifiers', 'Allergen', 'Tag', 'Item Modifier Group']

In [21]:
import pandas as pd

# Load all sheets into a dictionary of DataFrame objects
sheets_dict = pd.read_excel(
    "menu_desired_format/menu_desired.xlsx", sheet_name=None)


# List of sheet names to print
sheet_names = [
    'Menu', 'Category', 'Item', 'Category Items',  'Item Modifiers',
    'Modifier', 'Modifier Option', 'Modifier ModifierOptions',
]

# **Filled Using Input**
sheets_dict["Menu"]

,id,menuName,posDisplayName,menuDescription,picture,startTime,endTime,genericModifierId,restaurantId,sortOrder,settingId,posButtonColor
0,1,Campbell Menu,Campbell Menu,Campbell Menu,NaN,NaN,NaN,NaN,1,1,NaN,#e34032

## Reading Exportables

In [22]:
import pandas as pd

def read_this(path):
    # Try reading the CSV file with different encodings
    encodings = ['utf-8', 'latin1', 'ISO-8859-1']

    for encoding in encodings:
        try:
            df = pd.read_csv(
                path, encoding=encoding)
            
            return df
        except UnicodeDecodeError as e:
            pass

## Filling Category Sheet

In [23]:
import pandas as pd
parent_categories = read_this("menu_exported/Menu_Export.csv")
sub_categories = read_this("menu_exported/MenuGroup_Export.csv")

#drop columns
parent_categories = parent_categories[["Item ID", "Name"]]
parent_categories["Parent Id"] = None
sub_categories = sub_categories[[
    "Item ID", "Name", "Parent Id"]]  # , "Parent Id"


# Add empty rows to parent_categories DataFrame
num_empty_rows = len(sub_categories)
empty_rows = pd.DataFrame(
    {col: [None]*num_empty_rows for col in parent_categories.columns})
parent_categories = pd.concat([parent_categories, empty_rows], ignore_index=True)

# Fill the empty rows with data from emp
for i in range(num_empty_rows):
    parent_categories.iloc[-(i+1), parent_categories.columns.get_loc("Item ID")
                           ] = str(sub_categories.iloc[i]["Item ID"])
    parent_categories.iloc[-(i+1), parent_categories.columns.get_loc("Name")
                           ] = sub_categories.iloc[i]["Name"]
    parent_categories.iloc[-(i+1), parent_categories.columns.get_loc("Parent Id")
                           ] = str(sub_categories.iloc[i]["Parent Id"])

In [24]:
category = sheets_dict["Category"][0:0]

# id is Item ID in parent_categories
# categoryName is Name in parent_categories
# posDisplayName is Name in parent_categories
# kdsDisplayName is Name in parent_categories
# parentCategoryId is Parent Id in parent_categories
# menuIds is 1 always

# **Fill the sheets_dict["Category"] using parent_categories**
# Fill the 'category' DataFrame using 'parent_categories'
category['id'] = parent_categories['Item ID'].astype(str)
category['categoryName'] = parent_categories['Name']
category['posDisplayName'] = parent_categories['Name']
category['kdsDisplayName'] = parent_categories['Name']
category['parentCategoryId'] = parent_categories['Parent Id'].astype(str)
category['menuIds'] = 1

# Assign the filled DataFrame to 'sheets_dict["Category"]'
sheets_dict["Category"] = category
sheets_dict["Category"]

/tmp/ipykernel_1702960/2313756543.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['id'] = parent_categories['Item ID'].astype(str)
/tmp/ipykernel_1702960/2313756543.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['categoryName'] = parent_categories['Name']
/tmp/ipykernel_1702960/2313756543.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['posDisplayName'] = parent_categories['Name']
/tmp/ipykernel_1702960/2313756543.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['kdsDisplayName'] = parent_categories['Name']
/tmp/ipykernel_1702960/2313756543.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['parentCategoryId'] = parent_categories['Parent Id'].astype(str)
/tmp/ipykernel_1702960/2313756543.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  category['menuIds'] = 1

,id,categoryName,posDisplayName,parentCategoryId,image,kdsDisplayName,sortOrder,kioskImage,startTime,endTime,settingId,menuIds,tagIds
0,400000000124401815,Proposta Della Casa,Proposta Della Casa,None,NaN,Proposta Della Casa,NaN,NaN,NaN,NaN,NaN,1,NaN
1,400000000186055623,WINE,WINE,None,NaN,WINE,NaN,NaN,NaN,NaN,NaN,1,NaN
2,400000002361064806,Brisket & Big Reds,Brisket & Big Reds,None,NaN,Brisket & Big Reds,NaN,NaN,NaN,NaN,NaN,1,NaN
3,400000000124401823,INSALATE,INSALATE,None,NaN,INSALATE,NaN,NaN,NaN,NaN,NaN,1,NaN
4,400000002856218570,Top Shelf Reds,Top Shelf Reds,None,NaN,Top Shelf Reds,NaN,NaN,NaN,NaN,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2606,400000005015919352,Robert Weil Sekt Brut 15,Robert Weil Sekt Brut 15,400000000186067099,NaN,Robert Weil Sekt Brut 15,NaN,NaN,NaN,NaN,NaN,1,NaN
2607,400000032263753721,Conti Zecca 'Liranu' Negroamaro 18,Conti Zecca 'Liranu' Negroamaro 18,400000000271238761,NaN,Conti Zecca 'Liranu' Negroamaro 18,NaN,NaN,NaN,NaN,NaN,1,NaN
2608,400000000268254248,l'Arco Rosso Veronese 17,l'Arco Rosso Veronese 17,400000000268246650,NaN,l'Arco Rosso Veronese 17,NaN,NaN,NaN,NaN,NaN,1,NaN
2609,400000015281685783,Neyers Sage Canyon Red,Neyers Sage Canyon Red,400000000268246650,NaN,Neyers Sage Canyon Red,NaN,NaN,NaN,NaN,NaN,1,NaN
2610,400000023938979728,Ridge Grenache Blanc 20,Ridge Grenache Blanc 20,400000000186067255,NaN,Ridge Grenache Blanc 20,NaN,NaN,NaN,NaN,NaN,1,NaN

## Filling Item Sheet

In [25]:
items = sheets_dict["Item"][0:0]
menu_export = read_this("menu_exported/MenuItem_Export.csv")

# **Fill the sheets_dict["Item"] using parent_categories**
# Fill the 'category' DataFrame using 'parent_categories'
items['id'] = menu_export['Item ID'].astype(str)
items['itemName'] = menu_export['Name']
items['itemPrice'] = menu_export["Base Price"]

# Assign the filled DataFrame to 'sheets_dict["Category"]'
sheets_dict["Item"] = items
sheets_dict["Item"]

/tmp/ipykernel_1702960/2658068544.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items['id'] = menu_export['Item ID'].astype(str)
/tmp/ipykernel_1702960/2658068544.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items['itemName'] = menu_export['Name']
/tmp/ipykernel_1702960/2658068544.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  items['itemPrice'] = menu_export["Base Price"]

,id,itemName,itemDescription,itemPrice,itemPicture,landscapeImage,onlineImage,thirdPartyImage,kioskItemImage,calories,...,maxLimit,noMaxLimit,inheritTagsFromCategory,inheritModifiersFromCategory,settingId,stationIds,addonIds,taxIds,tagIds,allergenIds
0,400000028298899835,RET LCN Nebbiolo,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400000038743222155,Fennochio Spetacol Nebbiolo,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400000001599465918,RET Lapierre Pacalet Julienas 17,NaN,36.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400000000418320852,Regular,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400000002279413810,Sale,NaN,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,400000002397872504,WC,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7976,400000017541114230,RET Conti Zecca Primitivo 18,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7977,400000003250776435,6/+,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7978,400000005015937990,RET Domaine Belle Crozes Hermitage 16,NaN,31.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7979,400000039374677528,BTL Ridge Grenache Blanc,NaN,65.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Filling Modifier Sheet

In [26]:
modifier = sheets_dict["Modifier"][0:0]
menu_export = read_this("menu_exported/MenuOptionGroup_Export.csv")

# **Fill the sheets_dict["Modifier"] using parent_categories**
# Fill the 'category' DataFrame using 'parent_categories'
modifier['id'] = menu_export['Item ID'].astype(str)
modifier['modifierName'] = menu_export['Name']
modifier['price'] = menu_export["Base Price"]

# Assign the filled DataFrame to 'sheets_dict["Category"]'
sheets_dict["Modifier"] = modifier
sheets_dict["Modifier"]

/tmp/ipykernel_1702960/163742009.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier['id'] = menu_export['Item ID'].astype(str)
/tmp/ipykernel_1702960/163742009.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier['modifierName'] = menu_export['Name']
/tmp/ipykernel_1702960/163742009.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier['price'] = menu_export["Base Price"]

,id,modifierName,posDisplayName,limit,price,multiSelect,parentModifierId,isNested,addNested,isOptional,...,isSizeModifier,prefix,pizzaSelection,showOnPos,showOnKiosk,showOnMpos,showOnQR,showOnline,showOnThirdParty,limitIndividualModifierSelection
0,400000002684672460,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400000002669203196,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400000002279413803,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400000002057746922,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400000001995538058,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,400000000593204206,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,400000005139625157,DESSERT,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
588,400000003973213643,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,400000003930446393,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,400000001499726566,Size,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Filling Modifier Options

In [27]:
sheets_dict["Modifier Option"][0:1]

,id,optionName,posDisplayName,kdsDisplayName,price,isStockAvailable,isSizeModifier
0,1,Classic,Classic,Classic,0,True,False

In [28]:
modifier_option = sheets_dict["Modifier Option"][0:0]
menu_export = read_this("menu_exported/MenuOption_Export.csv")

# **Fill the sheets_dict["Modifier"] using parent_categories**
# Fill the 'category' DataFrame using 'parent_categories'

modifier_option['id'] = menu_export['Item ID'].astype(str)
modifier_option['optionName'] = menu_export['Name']
modifier_option['posDisplayName'] = menu_export['Name']
modifier_option['kdsDisplayName'] = menu_export['Name']
modifier_option['price'] = menu_export["Base Price"]

# Assign the filled DataFrame to 'sheets_dict["Category"]'
sheets_dict["Modifier Option"] = modifier_option
sheets_dict["Modifier Option"]

/tmp/ipykernel_1702960/1988840591.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier_option['id'] = menu_export['Item ID'].astype(str)
/tmp/ipykernel_1702960/1988840591.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier_option['optionName'] = menu_export['Name']
/tmp/ipykernel_1702960/1988840591.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier_option['posDisplayName'] = menu_export['Name']
/tmp/ipykernel_1702960/1988840591.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier_option['kdsDisplayName'] = menu_export['Name']
/tmp/ipykernel_1702960/1988840591.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  modifier_option['price'] = menu_export["Base Price"]

,id,optionName,posDisplayName,kdsDisplayName,price,isStockAvailable,isSizeModifier
0,400000000270493257,1/4 lb.,1/4 lb.,1/4 lb.,5.27,NaN,NaN
1,400000004461165041,6/+,6/+,6/+,15.58,NaN,NaN
2,400000004397099646,Sale 6/+,Sale 6/+,Sale 6/+,28.00,NaN,NaN
3,400000000877550497,WC,WC,WC,18.00,NaN,NaN
4,400000002128382484,Regular,Regular,Regular,23.00,NaN,NaN
...,...,...,...,...,...,...,...
1463,400000002397915491,Regular,Regular,Regular,35.00,NaN,NaN
1464,400000003259313759,Regular,Regular,Regular,55.00,NaN,NaN
1465,400000000877702861,6+,6+,6+,20.00,NaN,NaN
1466,400000000124840876,No Parsley,No Parsley,No Parsley,0.00,NaN,NaN
1467,400000003930446395,Regular,Regular,Regular,24.00,NaN,NaN

## Filling Category Items

In [29]:
sheets_dict["Category Items"][0:1]

   id  categoryId  itemId  sortOrder
0   1           7       1          1

In [30]:
item_modifier_report = read_this(
    "menu_exported/ItemSelectionDetails.csv")

# create a json with key as Sales Category, and Menu Item as list of values
item_modifier_report_dict = item_modifier_report.groupby("Sales Category")[
    "Menu Item"].apply(list).to_dict()




# Compare Sales Category to categoryName, if same then get id from sheets_dict["Category"]
category_ids = sheets_dict["Category"][["id", "categoryName"]]
category_ids
item_ids = sheets_dict["Item"][["id", "itemName"]]
item_ids

                      id                               itemName
0     400000028298899835                       RET LCN Nebbiolo
1     400000038743222155            Fennochio Spetacol Nebbiolo
2     400000001599465918       RET Lapierre Pacalet Julienas 17
3     400000000418320852                                Regular
4     400000002279413810                                   Sale
...                  ...                                    ...
7975  400000002397872504                                     WC
7976  400000017541114230           RET Conti Zecca Primitivo 18
7977  400000003250776435                                    6/+
7978  400000005015937990  RET Domaine Belle Crozes Hermitage 16
7979  400000039374677528               BTL Ridge Grenache Blanc

[7980 rows x 2 columns]

In [31]:
import pandas as pd

# Create the mapping dictionaries (assuming these are already defined)
category_id_map = dict(zip(category_ids["categoryName"], category_ids["id"]))
item_id_map = dict(zip(item_ids["itemName"], item_ids["id"]))

# Create item_modifier_report_dict_ids with error handling
item_modifier_report_dict_ids = {}

for sales_category, menu_items in item_modifier_report_dict.items():
    if sales_category in category_id_map:
        category_id = category_id_map[sales_category]
        item_ids_list = []
        for menu_item in menu_items:
            if menu_item in item_id_map:
                item_ids_list.append(item_id_map[menu_item])
            else:
                print(
                    f"Warning: Menu Item '{menu_item}' not found in item_id_map")
        item_modifier_report_dict_ids[category_id] = item_ids_list
    else:
        print(
            f"Warning: Sales Category '{sales_category}' not found in category_id_map")

# Prepare the data for the new DataFrame
rows = []
sort_order = None  # Starting sort order

for category_id, item_ids in item_modifier_report_dict_ids.items():
    for item_id in item_ids:
        rows.append({"id": len(rows) + 1, "categoryId": category_id,
                    "itemId": item_id, "sortOrder": sort_order})
        sort_order = None

# Create the DataFrame
category_items_df = pd.DataFrame(
    rows, columns=["id", "categoryId", "itemId", "sortOrder"])

# Fill the sheets_dict["Category Items"][0:0] with the new data
sheets_dict["Category Items"] = category_items_df

# Print the resulting DataFrame
sheets_dict["Category Items"]

Warning: Sales Category 'Bottled Beer' not found in category_id_map
Warning: Sales Category 'Events' not found in category_id_map
Warning: Menu Item 'Sausage  Provolone Fritatta' not found in item_id_map
Warning: Menu Item 'Provolone Sausage' not found in item_id_map
Warning: Menu Item 'Grilled Cheese' not found in item_id_map
Warning: Menu Item 'Chicken Breast With Asaragus' not found in item_id_map
Warning: Menu Item 'Sausage & Provolone' not found in item_id_map
Warning: Menu Item 'Sausage And Provolone' not found in item_id_map
Warning: Menu Item 'Spring Rav' not found in item_id_map
Warning: Sales Category 'NA Beverage' not found in category_id_map
Warning: Sales Category 'Retail Wine' not found in category_id_map
Warning: Sales Category 'Wine Club Retail' not found in category_id_map
Warning: Sales Category 'Wine on Premise' not found in category_id_map

        id          categoryId              itemId sortOrder
0        1  400000001573057547  400000000124429510      None
1        2  400000001573057547  400000007314553611      None
2        3  400000001573057547  400000000124807686      None
3        4  400000001573057547  400000038674184117      None
4        5  400000001573057547  400000039509345665      None
...    ...                 ...                 ...       ...
2806  2807  400000001573057547  400000018383162672      None
2807  2808  400000001573057547  400000000124807686      None
2808  2809  400000001573057547  400000000278261923      None
2809  2810  400000001573057547  400000018383162676      None
2810  2811  400000001573057547  400000018383162678      None

[2811 rows x 4 columns]

## Filling Item Modifiers

In [32]:
sheets_dict["Item Modifiers"][0:1]

   itemId  modifierId  sortOrder
0       2           2          1

In [33]:
modifier_group_report = read_this(
    "menu_exported/ItemModifierSelectionDetails.csv")

# Group by "Parent Menu Selection" and create lists of "Option Group Name"
item_modifier_report_dict = (
    modifier_group_report.groupby("Parent Menu Selection")["Option Group Name"]
    .apply(lambda x: [item for item in x if pd.notna(item)])
    .to_dict()
)


# Compare Sales Category to categoryName, if same then get id from sheets_dict["Category"]
item_ids = sheets_dict["Item"][["id", "itemName"]]
modifier_ids = sheets_dict["Modifier"][["id", "modifierName"]]

modifier_group_report

,Location,Order #,Sent Date,Modifier,Option Group Name,Parent Menu Selection,Discount,Net Price,Qty,Void?,Void Reason
0,Los Gatos,2,4/1/24 12:02 PM,Castelvetrano Only,NaN,3 Olive Sampler,0.0,0.0,1.0,False,NaN
1,Los Gatos,1,4/1/24 12:07 PM,Add Roma Tomatoes,Burrata Options,DiStefano Burrata,0.0,5.0,1.0,False,NaN
2,Los Gatos,1,4/1/24 12:33 PM,Add 5 Shrimp,Pasta Options,Carbonara,0.0,12.0,1.0,False,NaN
3,Los Gatos,4,4/1/24 12:35 PM,Crumbles On The Side,NaN,1/2 Gorgonzola,0.0,0.0,1.0,False,NaN
4,Los Gatos,11,4/1/24 1:38 PM,Extra Dressing,NaN,Caesar,0.0,0.0,1.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
551,Los Gatos,39,4/30/24 7:37 PM,Add Shrimp,Insalate Options,Gorgonzola Salad,0.0,12.0,1.0,False,NaN
552,Los Gatos,39,4/30/24 7:37 PM,Add Chicken,Insalate Options,Mista,0.0,9.0,1.0,False,NaN
553,Los Gatos,39,4/30/24 7:37 PM,On The Mista,NaN,Herb Chicken,0.0,0.0,1.0,False,NaN
554,Los Gatos,39,4/30/24 7:37 PM,Add One Meatball,Pasta Options,Aglio e Olio,0.0,7.0,1.0,False,NaN
555,Los Gatos,39,4/30/24 7:37 PM,Add Mozzerella,Options,Meatballs,0.0,3.0,1.0,False,NaN

In [34]:
import pandas as pd

# Create the mapping dictionaries (assuming these are already defined)
item_id_map = dict(zip(item_ids["itemName"], item_ids["id"]))
modifier_id_map = dict(zip(modifier_ids["modifierName"], modifier_ids["id"]))

# Create item_modifier_report_dict_ids with error handling
item_modifier_report_dict_ids = {}

for menu_item, modifiers in item_modifier_report_dict.items():
    if menu_item in item_id_map:
        item_id = item_id_map[menu_item]
        modifier_ids_list = []
        for modifier in modifiers:
            if modifier in modifier_id_map:
                modifier_ids_list.append(modifier_id_map[modifier])
            else:
                print(
                    f"Warning: Modifier '{modifier}' not found in modifier_id_map")
        item_modifier_report_dict_ids[item_id] = modifier_ids_list
    else:
        print(f"Warning: Menu Item '{menu_item}' not found in item_id_map")

# Prepare the data for the new DataFrame
rows = []
sort_order = None  # Starting sort order

for item_id, modifier_ids in item_modifier_report_dict_ids.items():
    for modifier_id in modifier_ids:
        rows.append({"id": len(rows) + 1, "itemId": item_id,
                    "modifierId": modifier_id, "sortOrder": sort_order})
        sort_order = None

# Create the DataFrame
item_modifiers_df = pd.DataFrame(
    rows, columns=["id", "itemId", "modifierId", "sortOrder"])

# Fill the sheets_dict["Item Modifiers"][0:0] with the new data
sheets_dict["Item Modifiers"] = item_modifiers_df

# Print the resulting DataFrame
sheets_dict["Item Modifiers"]

      id              itemId          modifierId sortOrder
0      1  400000007553395196  400000000124864383      None
1      2  400000007553395198  400000000124864383      None
2      3  400000000124429510  400000000268096172      None
3      4  400000000124807686  400000000160213473      None
4      5  400000000124807686  400000000124949092      None
..   ...                 ...                 ...       ...
301  302  400000000124803254  400000000267937756      None
302  303  400000000124803254  400000000267937756      None
303  304  400000000124437127  400000000267937756      None
304  305  400000000124437127  400000000268102507      None
305  306  400000000124422600  400000011531244453      None

[306 rows x 4 columns]

## Filling Modifier and Modifier Options

In [35]:
sheets_dict["Modifier ModifierOptions"][0:1]

   modifierId  modifierOptionId  isDefaultSelected  maxLimit
0           1                 1              False         1

In [36]:
import pandas as pd

# Read the modifier group report
modifier_group_report = read_this(
    "menu_exported/ItemModifierSelectionDetails.csv")

# Group by "Modifier" and create lists of "Option Group Name"
modifier_group_report_dict = (
    modifier_group_report.groupby("Modifier")["Option Group Name"]
    .apply(lambda x: [item for item in x if pd.notna(item)])
    .to_dict()
)

# Compare Sales Category to categoryName, if same then get id from sheets_dict["Category"]
modifier_ids = sheets_dict["Modifier"][["id", "modifierName"]]

modifier_group_report

,Location,Order #,Sent Date,Modifier,Option Group Name,Parent Menu Selection,Discount,Net Price,Qty,Void?,Void Reason
0,Los Gatos,2,4/1/24 12:02 PM,Castelvetrano Only,NaN,3 Olive Sampler,0.0,0.0,1.0,False,NaN
1,Los Gatos,1,4/1/24 12:07 PM,Add Roma Tomatoes,Burrata Options,DiStefano Burrata,0.0,5.0,1.0,False,NaN
2,Los Gatos,1,4/1/24 12:33 PM,Add 5 Shrimp,Pasta Options,Carbonara,0.0,12.0,1.0,False,NaN
3,Los Gatos,4,4/1/24 12:35 PM,Crumbles On The Side,NaN,1/2 Gorgonzola,0.0,0.0,1.0,False,NaN
4,Los Gatos,11,4/1/24 1:38 PM,Extra Dressing,NaN,Caesar,0.0,0.0,1.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
551,Los Gatos,39,4/30/24 7:37 PM,Add Shrimp,Insalate Options,Gorgonzola Salad,0.0,12.0,1.0,False,NaN
552,Los Gatos,39,4/30/24 7:37 PM,Add Chicken,Insalate Options,Mista,0.0,9.0,1.0,False,NaN
553,Los Gatos,39,4/30/24 7:37 PM,On The Mista,NaN,Herb Chicken,0.0,0.0,1.0,False,NaN
554,Los Gatos,39,4/30/24 7:37 PM,Add One Meatball,Pasta Options,Aglio e Olio,0.0,7.0,1.0,False,NaN
555,Los Gatos,39,4/30/24 7:37 PM,Add Mozzerella,Options,Meatballs,0.0,3.0,1.0,False,NaN

In [37]:


# Create the mapping dictionary for modifiers (assuming these are already defined)
modifier_id_map = dict(zip(modifier_ids["modifierName"], modifier_ids["id"]))

# Create modifier_group_report_dict_ids with error handling
modifier_group_report_dict_ids = {}

for modifier, option_groups in modifier_group_report_dict.items():
    if modifier in modifier_id_map:
        modifier_id = modifier_id_map[modifier]
        option_group_ids_list = []
        for option_group in option_groups:
            if option_group in modifier_id_map:
                option_group_ids_list.append(modifier_id_map[option_group])
            else:
                print(
                    f"Warning: Option Group '{option_group}' not found in modifier_id_map")
        modifier_group_report_dict_ids[modifier_id] = option_group_ids_list
    else:
        print(f"Warning: Modifier '{modifier}' not found in modifier_id_map")

# Prepare the data for the new DataFrame
rows = []

for modifier_id, option_group_ids in modifier_group_report_dict_ids.items():
    for option_group_id in option_group_ids:
        rows.append({
            "modifierId": modifier_id,
            "modifierOptionId": option_group_id,
            "isDefaultSelected": False,
            "maxLimit": 1
        })

# Create the DataFrame
modifiers_groups_df = pd.DataFrame(
    rows, columns=["modifierId", "modifierOptionId", "isDefaultSelected", "maxLimit"])

# Fill the sheets_dict["Modifier Groups"][0:0] with the new data
sheets_dict["Modifier ModifierOptions"] = modifiers_groups_df

# Print the resulting DataFrame
print(sheets_dict["Modifier ModifierOptions"])

Warning: Modifier '2 Bolzano' not found in modifier_id_map
Warning: Modifier '2 Bolzano 1 Funghi' not found in modifier_id_map
Warning: Modifier '2 Calabrese, One Other Salame' not found in modifier_id_map
Warning: Modifier '2 Shrimp Sides' not found in modifier_id_map
Warning: Modifier '2 Tricolore' not found in modifier_id_map
Warning: Modifier '2tricolore No Funghi' not found in modifier_id_map
Warning: Modifier '4 Funghi, 1 Bolzano' not found in modifier_id_map
Warning: Modifier 'Add 5 Shrimp' not found in modifier_id_map
Warning: Modifier 'Add Anchovy' not found in modifier_id_map
Warning: Modifier 'Add Arugula' not found in modifier_id_map
Warning: Modifier 'Add Arugula And Lemon' not found in modifier_id_map
Warning: Modifier 'Add Chicken Well Done' not found in modifier_id_map
Warning: Modifier 'Add Garlic Chili' not found in modifier_id_map
Warning: Modifier 'Add Giardinera' not found in modifier_id_map
Warning: Modifier 'Add Giardiniera' not found in modifier_id_map
Warning: Modifier 'Add Lonzino' not found in modifier_id_map
Warning: Modifier 'Add Mozz, No Sauce' not found in modifier_id_map
Warning: Modifier 'Add Mozzerella' not found in modifier_id_map
Warning: Modifier 'Add One Meatball' not found in modifier_id_map
Warning: Modifier 'Add Pepperchini' not found in modifier_id_map
Warning: Modifier 'Add Pesto' not found in modifier_id_map
Warning: Modifier 'Add Pistachios' not found in modifier_id_map
Warning: Modifier 'Add Prosciutto' not found in modifier_id_map
Warning: Modifier 'Add Red Sauce' not found in modifier_id_map
Warning: Modifier 'Add Roma Tomatoes' not found in modifier_id_map
Warning: Modifier 'Add Salame' not found in modifier_id_map
Warning: Modifier 'Add Salmon' not found in modifier_id_map
Warning: Modifier 'Add Shrimp ' not found in modifier_id_map
Warning: Modifier 'Add Sliced Tomatoes' not found in modifier_id_map
Warning: Modifier 'Add Spaghetti' not found in modifier_id_map
Warning: Modifier 'Add Spring Mix Light Cheese' not found in modifier_id_map
Warning: Modifier 'Add Susage And Veggies' not found in modifier_id_map
Warning: Modifier 'Add To Kids Pasta' not found in modifier_id_map
Warning: Modifier 'Add Tomatoes' not found in modifier_id_map
Warning: Modifier 'Add Tonno' not found in modifier_id_map
Warning: Modifier 'Add Two Meatballs' not found in modifier_id_map
Warning: Modifier 'Add Veggies' not found in modifier_id_map
Warning: Modifier 'All Cheese' not found in modifier_id_map
Warning: Modifier 'All Cheese But Duck Salami' not found in modifier_id_map
Warning: Modifier 'All Green' not found in modifier_id_map
Warning: Modifier 'Anchovies' not found in modifier_id_map
Warning: Modifier 'Anchovy' not found in modifier_id_map
Warning: Modifier 'Anchovy On Half' not found in modifier_id_map
Warning: Modifier 'Anchovy On The Side' not found in modifier_id_map
Warning: Modifier 'Arugula' not found in modifier_id_map
Warning: Modifier 'Arugula Only' not found in modifier_id_map
Warning: Modifier 'B Day' not found in modifier_id_map
Warning: Modifier 'Balsamic Viniagrette' not found in modifier_id_map
Warning: Modifier 'Bday' not found in modifier_id_map
Warning: Modifier 'Belleboolle' not found in modifier_id_map
Warning: Modifier 'Bolzano' not found in modifier_id_map
Warning: Modifier 'Both Split' not found in modifier_id_map
Warning: Modifier 'Bracifote Creek' not found in modifier_id_map
Warning: Modifier 'Butter' not found in modifier_id_map
Warning: Modifier 'Butter And Cheese' not found in modifier_id_map
Warning: Modifier 'Butter Pasta And Cheese' not found in modifier_id_map
Warning: Modifier 'Butter Pasta With Italian Sausage' not found in modifier_id_map
Warning: Modifier 'Calabrese' not found in modifier_id_map
Warning: Modifier 'Calabresse Please:)' not found in modifier_id_map
Warning: Modifier 'Castelvetrano' not found in modifier_id_map
Warning: Modifier 'Castelvetrano Only' not found in modifier_id_map
Warning: Modifier 'Castelvetranos' not found in modifier_id_map
Warning: Modifier 'Castelvetranos Only' not found in modifier_id_map
Warning: Modifier 'Castelveyrano' not found in modifier_id_map
Warning: Modifier 'Ceasar Dressing Instead Of Pesto' not found in modifier_id_map
Warning: Modifier 'Cheese: 4, 12, 18, 6' not found in modifier_id_map
Warning: Modifier 'Chili Flakes On Side' not found in modifier_id_map
Warning: Modifier 'Chili On Side' not found in modifier_id_map
Warning: Modifier 'Cook Pasta Longer' not found in modifier_id_map
Warning: Modifier 'Crumbles On The Side' not found in modifier_id_map
Warning: Modifier 'Cut 5' not found in modifier_id_map
Warning: Modifier 'Cut In 4' not found in modifier_id_map
Warning: Modifier 'DO NOT MAKE' not found in modifier_id_map
Warning: Modifier 'Dont Make' not found in modifier_id_map
Warning: Modifier 'Dressing On Side' not found in modifier_id_map
Warning: Modifier 'Dressing On The Side' not found in modifier_id_map
Warning: Modifier 'Edi Kante' not found in modifier_id_map
Warning: Modifier 'Ema' not found in modifier_id_map
Warning: Modifier 'Extra Cheese Pls:)' not found in modifier_id_map
Warning: Modifier 'Extra Crostini' not found in modifier_id_map
Warning: Modifier 'Extra Dressing' not found in modifier_id_map
Warning: Modifier 'Extra Meat' not found in modifier_id_map
Warning: Modifier 'Extra Parm' not found in modifier_id_map
Warning: Modifier 'Extra Pepperoncini' not found in modifier_id_map
Warning: Modifier 'Extra Red Pepper' not found in modifier_id_map
Warning: Modifier 'Extra Veggies' not found in modifier_id_map
Warning: Modifier 'For Karla' not found in modifier_id_map
Warning: Modifier 'Full Salmon' not found in modifier_id_map
Warning: Modifier 'GLS' not found in modifier_id_map
Warning: Modifier 'Garlic Chili' not found in modifier_id_map
Warning: Modifier 'Gf Bread' not found in modifier_id_map
Warning: Modifier 'Giardinera' not found in modifier_id_map
Warning: Modifier 'Glutenfree' not found in modifier_id_map
Warning: Modifier 'Glutten Free' not found in modifier_id_map
Warning: Modifier 'Gorgonzola And Truffle' not found in modifier_id_map
Warning: Modifier 'Gruner Hum Hofer' not found in modifier_id_map
Warning: Modifier 'Half' not found in modifier_id_map
Warning: Modifier 'Half No Burrata' not found in modifier_id_map
Warning: Modifier 'Include Caprino' not found in modifier_id_map
Warning: Modifier 'Just Butter And Cheese' not found in modifier_id_map
Warning: Modifier 'Just Oil And Noodles' not found in modifier_id_map
Warning: Modifier 'L Arco Roso' not found in modifier_id_map
Warning: Modifier 'Large Side Of Cippolini Onions' not found in modifier_id_map
Warning: Modifier 'Lemon On Sids' not found in modifier_id_map
Warning: Modifier 'Lettuce Not Spring Mix' not found in modifier_id_map
Warning: Modifier 'Light Chili' not found in modifier_id_map
Warning: Modifier 'Light Dressing' not found in modifier_id_map
Warning: Modifier 'Light Oil' not found in modifier_id_map
Warning: Modifier 'Likes Truffle' not found in modifier_id_map
Warning: Modifier 'Lite Chili' not found in modifier_id_map
Warning: Modifier 'Lorano' not found in modifier_id_map
Warning: Modifier 'Make One Of The Cheeses Burrata' not found in modifier_id_map
Warning: Modifier 'Meatball On Side' not found in modifier_id_map
Warning: Modifier 'Meatball On Side Pls' not found in modifier_id_map
Warning: Modifier 'Med Rare' not found in modifier_id_map
Warning: Modifier 'Mixed Greens No Romaine' not found in modifier_id_map
Warning: Modifier 'Mixed With Balsamic' not found in modifier_id_map
Warning: Modifier 'Mortadella And Genoa Panini, With Butter' not found in modifier_id_map
Warning: Modifier 'Mt Eden Chard' not found in modifier_id_map
Warning: Modifier 'NO MAKE' not found in modifier_id_map
Warning: Modifier 'Nada Picante' not found in modifier_id_map
Warning: Modifier 'No Basil Cheese On Side' not found in modifier_id_map
Warning: Modifier 'No Bread Crumbs' not found in modifier_id_map
Warning: Modifier 'No Calabrese Y No Enchiloso' not found in modifier_id_map
Warning: Modifier 'No Chili' not found in modifier_id_map
Warning: Modifier 'No Chili ,no Letuce On Plate' not found in modifier_id_map
Warning: Modifier 'No Chili Flakes' not found in modifier_id_map
Warning: Modifier 'No Chili Or Breadcrumbs' not found in modifier_id_map
Warning: Modifier 'No Chili Spread' not found in modifier_id_map
Warning: Modifier 'No Crumbles' not found in modifier_id_map
Warning: Modifier 'No Dressing' not found in modifier_id_map
Warning: Modifier 'No Dressing Vinagerette' not found in modifier_id_map
Warning: Modifier 'No Garlic' not found in modifier_id_map
Warning: Modifier 'No Goia Burrata' not found in modifier_id_map
Warning: Modifier 'No Gorgonzola' not found in modifier_id_map
Warning: Modifier 'No Make' not found in modifier_id_map
Warning: Modifier 'No Mista Sub Ceasar' not found in modifier_id_map
Warning: Modifier 'No Mushrooms' not found in modifier_id_map
Warning: Modifier 'No Onions' not found in modifier_id_map
Warning: Modifier 'No Onions On Falf' not found in modifier_id_map
Warning: Modifier 'No Pecorino' not found in modifier_id_map
Warning: Modifier 'No Pepper' not found in modifier_id_map
Warning: Modifier 'No Provolone Sub Montemayore ,pressed' not found in modifier_id_map
Warning: Modifier 'No Renata' not found in modifier_id_map
Warning: Modifier 'No Renata Add Fungi' not found in modifier_id_map
Warning: Modifier 'No Salt' not found in modifier_id_map
Warning: Modifier 'No Side Of Greenz' not found in modifier_id_map
Warning: Modifier 'No Spicy' not found in modifier_id_map
Warning: Modifier 'No Truffle' not found in modifier_id_map
Warning: Modifier 'No Truffle ,no Truffle Oil' not found in modifier_id_map
Warning: Modifier 'No Truffle Oil' not found in modifier_id_map
Warning: Modifier 'Normal And Bf Bread' not found in modifier_id_map
Warning: Modifier 'Odonata' not found in modifier_id_map
Warning: Modifier 'Odonata Chard' not found in modifier_id_map
Warning: Modifier 'Odonata Half' not found in modifier_id_map
Warning: Modifier 'On Board But Wrapped 4cheese 2 Meat' not found in modifier_id_map
Warning: Modifier 'On The Mista' not found in modifier_id_map
Warning: Modifier 'One Bennie Firm Eggs' not found in modifier_id_map
Warning: Modifier 'One Eggs No Focaccia' not found in modifier_id_map
Warning: Modifier 'One Has Sause On The Side' not found in modifier_id_map
Warning: Modifier 'One Meat And One Cheese Spicy' not found in modifier_id_map
Warning: Modifier 'Only Bright Green' not found in modifier_id_map
Warning: Modifier 'Only Green' not found in modifier_id_map
Warning: Modifier 'Only Green Olives' not found in modifier_id_map
Warning: Modifier 'Onlybgreen' not found in modifier_id_map
Warning: Modifier 'Pair With Meatballs' not found in modifier_id_map
Warning: Modifier 'Pepperoncini On Side' not found in modifier_id_map
Warning: Modifier 'Pressed' not found in modifier_id_map
Warning: Modifier 'Primitivo' not found in modifier_id_map
Warning: Modifier 'R8' not found in modifier_id_map
Warning: Modifier 'R8 Half' not found in modifier_id_map
Warning: Modifier 'Red Sauce No Oil' not found in modifier_id_map
Warning: Modifier 'Roma Tomatoes' not found in modifier_id_map
Warning: Modifier 'Ruminat' not found in modifier_id_map
Warning: Modifier 'Salmon' not found in modifier_id_map
Warning: Modifier 'Serbal' not found in modifier_id_map
Warning: Modifier 'Side Lemon' not found in modifier_id_map
Warning: Modifier 'Side Of Garlic Chili' not found in modifier_id_map
Warning: Modifier 'Side Of Sheimp' not found in modifier_id_map
Warning: Modifier 'Side Of Shrim!p' not found in modifier_id_map
Warning: Modifier 'Side Of Veggies' not found in modifier_id_map
Warning: Modifier 'Speck On The Side' not found in modifier_id_map
Warning: Modifier 'Sub Funghi For Tricolore' not found in modifier_id_map
Warning: Modifier 'Sub Funghi With Bolzano' not found in modifier_id_map
Warning: Modifier 'Sugar' not found in modifier_id_map
Warning: Modifier 'Tenuta Alfonso' not found in modifier_id_map
Warning: Modifier 'Tenuta Fulavin' not found in modifier_id_map
Warning: Modifier 'To Go' not found in modifier_id_map
Warning: Modifier 'Top With Basil' not found in modifier_id_map
Warning: Modifier 'Well Done Chicken' not found in modifier_id_map
Warning: Modifier 'Westgate Curtis' not found in modifier_id_map
Warning: Modifier 'With Milk' not found in modifier_id_map
Warning: Modifier 'Xtra Dressing' not found in modifier_id_map
Warning: Modifier 'Xtra Lemon On The Side' not found in modifier_id_map
Warning: Modifier 'Xtra Peperunci I' not found in modifier_id_map
Warning: Modifier 'Xtra Peperuncini' not found in modifier_id_map
Warning: Modifier 'Xtra Veggies' not found in modifier_id_map
Warning: Modifier 'Xtra Vegies' not found in modifier_id_map
Warning: Modifier 'with Bread' not found in modifier_id_map
            modifierId    modifierOptionId  isDefaultSelected  maxLimit
0   400000021874887824  400000000124864383              False         1
1   400000021874887824  400000000124864383              False         1
2   400000021874887824  400000000124864383              False         1
3   400000021874887824  400000000160213473              False         1
4   400000021874887824  400000000124864383              False         1
..                 ...                 ...                ...       ...
83  400000000267930876  400000000160213473              False         1
84  400000000267930876  400000000160213473              False         1
85  400000000267936910  400000000268102507              False         1
86  400000000267936910  400000000268102507              False         1
87  400000000267936910  400000000268102507              False         1

[88 rows x 4 columns]

In [38]:
# save sheets dict to xlsx
with pd.ExcelWriter("Menu.xlsx") as writer:
    for sheet_name, df in sheets_dict.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)